### ISSUE TITLE
YYYY is the wrong timestamp format

### ISSUE THREAD

**Issue by jsaedtler** [aws-samples/aws-blog-firehose-custom-prefixes-for-s3-objects#1]
When using the example, firehose dumps events arriving on 2019-12-29 to 31 to 
YYYY=>2020 instead of 2019.

This happens because YYYY is the year of the calendar week. The correct timestamp format is yyyy. yyyy is the normal year.

See: https://github.com/aws-samples/aws-blog-firehose-custom-prefixes-for-s3-objects/blob/master/createdeliverystream.json#L7

**Comment by rcchakr** [comment]
Thank You for pointing this out. Made the change.
